[package]
name = "c0nsume_qwen_frontend"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "*"
actix-files = "*"
serde = { version = "*", features = ["derive"] }
reqwest = { version = "*", features = ["json", "multipart"] }

serde_json = "1"